#! /usr/bin/env python

from cassandra_cql import cql_execute
from sys import argv

if len(argv) < 4 or (len(argv) == 5 and argv[4] != '-f'):
    print '''
This file is used to inject a full *.cql file into a Cassandra database.
To run this script, all three command line parameters are required:
    
    python cassandra-cql.py hostname port script_file [-f]

        hostname     The address of the server you are connecting to
        port         The port of the cassandra server (usually 9160)
        script_file  The *.cql file to be executed
        -f           Force the script to continue if it hits any error 

An example script file would be:

    USE keyspace;

    CREATE COLUMNFAMILY projects (
      KEY uuid PRIMARY KEY,
      project_id int,
      name text
    );
    '''
else:
    cql_execute(argv[1], argv[2], argv[3], force=(len(argv) > 4))
